// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJVRAtI2VQx82Ik2-wQjkIX4uW78k12FE',
    appId: '1:743411420757:web:85783e89077d56e7ec4edc',
    messagingSenderId: '743411420757',
    projectId: 'fir-53511',
    authDomain: 'fir-53511.firebaseapp.com',
    storageBucket: 'fir-53511.appspot.com',
    measurementId: 'G-K9PJW4J55J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoyG1VhThDzpMaZilrWiJTTA3lf3HzZnE',
    appId: '1:743411420757:android:0a581facc9483149ec4edc',
    messagingSenderId: '743411420757',
    projectId: 'fir-53511',
    storageBucket: 'fir-53511.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv7sBd9IMwPCpzdykR-8YsQ_VZTg9a-10',
    appId: '1:743411420757:ios:434ad8a52df26d1fec4edc',
    messagingSenderId: '743411420757',
    projectId: 'fir-53511',
    storageBucket: 'fir-53511.appspot.com',
    iosClientId: '743411420757-gsni7c6urvva6j8g1ng1m1kc56gbmdt8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv7sBd9IMwPCpzdykR-8YsQ_VZTg9a-10',
    appId: '1:743411420757:ios:1e1045a926541cb0ec4edc',
    messagingSenderId: '743411420757',
    projectId: 'fir-53511',
    storageBucket: 'fir-53511.appspot.com',
    iosClientId: '743411420757-o06ibvimb732sbosddp05p8tksa9kata.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
